### ISSUE TITLE
Setup soft-failed for shodan_dns: No API key set

### ISSUE THREAD

**Issue by stalane** [blacklanternsecurity/bbot#1023]
Setup soft-failed for shodan_dns: No API key set

Correct API key is in secrets.yml and is being parsed into config. 
`boot --current-config` shows API key at the end of output. 

What am I doing wrong here?

**Comment by TheTechromancer** [comment]
Are you sure the config is in the right format? It should be:

```yaml
modules:
  shodan_dns:
    api_key: <api_key>
```
