### ISSUE TITLE
Discord webhook in bbot.yaml does not work

### ISSUE THREAD

**Issue by cosad3s** [blacklanternsecurity/bbot#1158]
**Describe the bug**

When the discord webhook is specified in bbot.yaml instead of command line, then the webhook is not called.

**Expected behavior**

Have the messages in the Discord channel when the webhook is specified in the bbot.yaml file.

**BBOT Command**

Any bbot command.

**OS, BBOT Installation Method + Version**

```bash
❯ bbot --version
v1.1.6
```

On Kali Linux

**BBOT Config (does not work), located in `~/.config/bbot/bbot.yml`:**

```yaml
output_modules:
  discord:
    webhook_url: output_modules.discord.webhook_url=https://discord.com/api/webhooks/1234/WEBHOOK
    event_types:
      - VULNERABILITY
      - FINDING
      - STORAGE_BUCKET
```

*(I followed the doc at https://www.blacklanternsecurity.com/bbot/scanning/output/)*
I tried also with:
    `- webhook_url: 'output_modules.discord.webhook_url=https://discord.com/api/webhooks/1234/WEBHOOK'`
    `- webhook_url: https://discord.com/api/webhooks/1234/WEBHOOK`

Work with: `bbot -om discord -c output_modules.discord.webhook_url=https://discord.com/api/webhooks/1234/WEBHOOK -t target`

**Logs**

No relevant discord stuff when `--debug` is enabled.

**Screenshots**

N/A

**Comment by TheTechromancer** [comment]
Thanks for noticing this, it's a typo in the documentation. In the yaml, you don't need to include the dot syntax:

```yaml
output_modules:
  discord:
    webhook_url: https://discord.com/api/webhooks/1234/deadbeef 
```
