### ISSUE TITLE
Run Tests on Multiple Linux Distros

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1469]
We should try and run our tests on multiple Linux distros. This would help prevent some of the cross-distro pain we've dealt with in installing OS packages.

```yaml
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, debian, archlinux, fedora-latest, gentoo, alpine]
```
