### ISSUE TITLE
How to add multiple api keys per service? 

### ISSUE THREAD

**Issue by DrorDvash** [blacklanternsecurity/bbot#1601]
**Describe the bug**
Most of the modules (services) allow you to sign up for a free account with a limited quota per api token. How can I insert more than one token? Does the tool know how to read several tokens for one module and rotate them so that they don't run out quickly and impact the results of scan? 

Something like that:
```
modules:
  shodan_dns:
    api_keys:
      - 'api_key_1'
      - 'api_key_2'
```

**Comment by Sh4d0wHunt3rX** [comment]
Hey : ) I guess this can be duplicate of #954 somehow.

Currently, no support of multiple API support : (

**Comment by DrorDvash** [comment]
When BBOT using a tool like subfinder, and subfinder has its own config file for api keys (and supports multiple), BBOT using it?

**Comment by TheTechromancer** [comment]
Yeah this is something we want to add in the future, but as of right now it's not supported. In the meantime my recommendation would be, if you really need that functionality, to take the output of subfinder and use it as BBOT's target list.

**Comment by DrorDvash** [comment]
Yea i was thinking to feed it up with associated domains or subdomains, 
Or just creating multiple secrets.yml and each scan to load a different one.

I just notice in the scan log that some services reach maximum capacity in one run. (3 domains as target)

**Comment by TheTechromancer** [comment]
Yeah I've noticed that as well. With how this feature is already supported in other tools, I think we can bump it to high priority.

**Comment by TheTechromancer** [comment]
@DrorDvash @Sh4d0wHunt3rX Thanks for your patience; this feature is finally merged!

You can now specify multiple API keys like so:

```yaml
config:
  modules:
    securitytrails:
      api_key:
        - 5bbf5a52328e7439ae6e719dfe712200
        - c193497a1a06b2c72230e6146ff47080
```
