### ISSUE TITLE
print subdomains directly

### ISSUE THREAD

**Issue by marcelo321** [blacklanternsecurity/bbot#1619]
Hello!

I just found this amazing tool, and wanted to implement it with some other tools like shadowclone and similars, and wanted to know if it would be possible to just have bbot print subdmains.

like: `bot --targets test -f subdomain-enum -s -y -o out -rf passive`

and only get subdomains as output, instead of saving them in /out/folder_name/subdomains.txt

**Comment by TheTechromancer** [comment]
Hey thanks for your interest in BBOT. 

Yes, this is possible by tweaking the options of the `stdout` module:

```bash
bbot -t microsoft.com -om stdout -c modules.stdout.event_types=[DNS_NAME] modules.stdout.accept_dupes=False modules.stdout.event_fields=[data]
```

Or as a preset:

```yaml
config:
  modules:
    stdout:
      event_types:
        - DNS_NAME
      event__fiels:
        - data
      accept_dupes: False
```

(Note that this will only work on 2.0, i.e. the `dev` branch)

However, I highly recommend against using BBOT with tools like shadowclone. The main value of BBOT is that it's recursive, but when you separate it into multiple instances, it prevents the recursion from happening properly. If this is your approach, simpler tools like subfinder/amass would probably work better.
