### ISSUE TITLE
--fast mode

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1874]
Sometimes we want to run BBOT against a bunch of pre-discovered hosts. We don't care about discovery; we just need it to go as fast as possible.

What we need is something like `--fast` that's essentially an alias for:

```yaml
# exclude excavate
exclude_modules:
  - excavate

config:
  # don't descend into subdomains
  scope:
    strict: true
  # do basic resolution but don't emit dns events
  dns:
    minimal: true
```

@aconite33
