### ISSUE TITLE
DNS Records Not Being Emitted By DNS Modules

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1903]
I have this DNS event in the image, it has "MX": ["mxb-00004003.gslb.pphosted.com"

![image](https://github.com/user-attachments/assets/a6312eec-d0cd-4e33-9f17-a51c1925c370)

But, there is no "module": "MX" anymore that reports mxb-00004003.gslb.pphosted.com for host wellsfargo.com

I have only 5 "module": "MX" in my whole output.json which all are affiliated. This is happenning for all of DNS records. For example, I have only 10 "module": "SOA" in the whole file which all are affiliated.

![image](https://github.com/user-attachments/assets/7d175688-baf8-40f8-ae63-a79ff7c0dea8)

This is the file:
[output.json](https://github.com/user-attachments/files/17588073/output.json)

Thanks

**Comment by TheTechromancer** [comment]
This seems to be working on my end. Have you checked your config?

![image](https://github.com/user-attachments/assets/21185e85-542a-4edc-a1b7-70c64662e1c7)

**Comment by Sh4d0wHunt3rX** [comment]
This is my config:
[bbot.zip](https://github.com/user-attachments/files/17589199/bbot.zip)

**Comment by TheTechromancer** [comment]
Hmm I don't see anything unusual in there. Can you post the output of `bbot --current-preset`?

**Comment by Sh4d0wHunt3rX** [comment]
```
root@mini:~# bbot --current-preset
  ______  _____   ____ _______
 |  ___ \|  __ \ / __ \__   __|
 | |___) | |__) | |  | | | |
 |  ___ <|  __ <| |  | | | |
 | |___) | |__) | |__| | | |
 |______/|_____/ \____/  |_|
 BIGHUGE BLS OSINT TOOL v2.1.1.5103rc

www.blacklanternsecurity.com/bbot

description: evil_peter
config:
  dns:
    brute_threads: 1000
  web_spider_distance: 1
  web_spider_depth: 2
  web_spider_links_per_page: 10
  modules:
    gowitness:
      resolution_x: 720
      resolution_y: 450
    portscan:
      ports: 7,9,13,21,22,23,25,26,37,53,69,79,80,81,88,106,110,111,113,119,123,135,137,138,139,143,144,161,162,179,199,389,427,443,444,445,465,500,512,513,514,515,541,543,544,548,553,554,563,587,623,624,631,636,646,873,990,993,995,1000,1025,1026,1027,1028,1029,1110,1241,1433,1434,1521,1720,1723,1755,1900,2000,2001,2049,2052,2053,2082,2083,2086,2087,2095,2096,2100,2121,2181,2375,2379,2380,2483,2484,2717,2888,3000,3128,3268,3269,3306,3389,3888,3986,4333,4786,4848,4899,5000,5009,5051,5060,5101,5190,5357,5432,5601,5631,5666,5800,5900,5901,5984,5985,6000,6001,6362,6379,6443,6646,6984,7001,7070,7473,7474,7687,8000,8001,8008,8009,8069,8080,8081,8086,8172,8181,8443,8444,8880,8888,9090,9092,9100,9200,9999,10000,10250,10257,10259,10443,16992,16993,27017,27018,27019,27080,32764,32768,49152,49153,49154,49155,49156,49157
    filedownload:
      extensions:
      - bak
      - bash
      - bashrc
      - conf
      - cfg
      - crt
      - csv
      - db
      - sqlite
      - doc
      - docx
      - exe
      - ica
      - indd
      - ini
      - jar
      - key
      - pub
      - log
      - markdown
      - md
      - msi
      - odg
      - odp
      - ods
      - odt
      - pdf
      - pem
      - pps
      - ppsx
      - ppt
      - pptx
      - ps1
      - raw
      - rdp
      - sh
      - sql
      - swp
      - sxw
      - tar
      - tar.gz
      - zip
      - txt
      - vbs
      - wpd
      - xls
      - xlsx
      - xml
      - yml
      - yaml
      - js
      - mjs
      - jsx
      - ts
      - vue
      - coffee
      - json
      - js.php
      - js.erb
      - map
      - bundle.js
      - cjs
    nuclei:
      templates: /root/.bbot/tools/nuclei-templates/shadow-hunter/selected-templates
      silent: true
    c99:
      api_key: XXX
    trickest:
      api_key: XXX
    chaos:
      api_key: XXX
    hunterio:
      api_key: XXX
    virustotal:
      api_key: XXX
    leakix:
      api_key: XXX
    securitytrails:
      api_key: XXX
    builtwith:
      api_key: XXX
    wpscan:
      api_key: XXX
    github_org:
      api_key: XXX
    zoomeye:
      api_key: XXX
    bevigil:
      api_key: XXX
    binaryedge:
      api_key: XXX
    shodan_dns:
      api_key: XXX
    github_codesearch:
      api_key: XXX

root@mini:~# 
```
