### ISSUE TITLE
host_header module runs for an incredible long time

### ISSUE THREAD

**Issue by aconite33** [blacklanternsecurity/bbot#2067]
**Describe the bug**
host_header module waiting 15+ minutes on an operation

**Expected behavior**
Shoudln't take 15+ minutes to run

**BBOT Command**
Example: `bbot -p preset.yml -t targets.txt -o ~/scans/`

**OS, BBOT Installation Method + Version**
`OS: Arch Linux, Installation poetry shell, dev

**BBOT Config**
```
config:
  interactsh_server: redacted
  interactsh_disable: false
  interactsh_token: redacted
exclude_modules:
- bypass403
- columbus
- hunt
- iis_shortnames
- smuggler
- url_manipulation
- dastardly
flags:
- email-enum
- subdomain-enum
- web-thorough
modules:
- baddns
- badsecrets
- dotnetnuke
- gowitness
- httpx
- robots
- telerik
output_modules:
- csv
- json
- subdomains
- txt
```

**Logs**
```
[DBUG]     host_header:                                                                                                                                                                   
[DBUG]         - host_header.handle_event(HTTP_RESPONSE("{'url': 'http://redacted.com/', 'timestamp': '2024-12-09T01:07:24.209677114Z',...", module=httpx, tags={'ip-89-44-80-26', 'in-s
cope', 'dir', 'status-302', 'http-title-object-moved'})) running for 16 minutes, 11 seconds:
```
