### ISSUE TITLE
Nuclei duplicate vulnerabilities when multiple urls redirect to same place

### ISSUE THREAD

**Issue by domwhewell-sage** [blacklanternsecurity/bbot#2253]
**Describe the bug**
Nuclei has scanned these 5 urls which have returned the same findings
- `http://redacted.com/`
- `https://redacted.com/membership/`
- `https://redacted.com/marketing/`
- `https://redacted.com/marketing/brand-guidelines/`
- `https://redacted.com/doc/`

The URLs `http://redacted.com/`,  `https://redacted.com/marketing/`, `https://redacted.com/marketing/brand-guidelines/`, `https://redacted.com/doc/` return a 302 to `Location: https://redacted.com/membership/?redirect=<original_url>`

This is the response from https://redacted.com/membership/
```bash
HTTP/2 302 Found
Date: Thu, 06 Feb 2025 09:23:23 GMT
Content-Type: text/html; charset=UTF-8
Location: https://redacted.com/wp-json/v1/sso/attach?broker=SSOBrokerprod&token=qwryqzgwqr4ss048k08sg00s0c8gs8gkoc84w8os04ogscww4&checksum=wp2pwixpzc0g88sgwws00cssckggs048k0k0g00c0o8s0o004&return_url=https%3A%2F%2Fredacted.com%2Fmembership%2F
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Link: <https://redacted.com/?p=2>; rel=shortlink
Cf-Cache-Status: DYNAMIC
Set-Cookie: PHPSESSID=f6f24e106efc8ff6794a4f17ede44c9e; path=/
Set-Cookie: __cf_bm=bwBmYUjJVnVmcQ.30Q.q_OzqA_R35JA60hB070JG6N4-1738833803-1.0.1.1-lhR9piCKQTF1iMs1A1kaXvkmp4ViT3BsVrvd7CyvktP6QkHn6e93gV2j1hFEHxjwJv9_FVYxuyJn3ZoxWgKWvA; path=/; expires=Thu, 06-Feb-25 09:53:23 GMT; domain=.redacted.com; HttpOnly; Secure; SameSite=None
Server: cloudflare
Cf-Ray: 90da14c799d2bec1-LHR
```

**Expected behavior**
The nuclei module could filter out responses where it redirects to a url already scanned. I'm not sure how doable this is given the main page `/membership/` redirects as well :/

**Preset**
```yaml
description: A custom preset to dnsbruteforce, portscan, fuzz urls and scan with nuclei

flags:
  - subdomain-enum
  - portscan
  - subdomain-hijack

modules:
  - ffuf
  - nuclei

output_modules:
  - teams

exclude_flags:
  - slow

config:
  web:
    spider_distance: 2
    spider_depth: 4
    spider_links_per_page: 25
  modules:
    dnsbrute:
      wordlist: /root/dns_wordlist.txt
    iis_shortnames:
      detect_only: false
    ffuf:
      wordlist: /root/url_wordlist.txt
      depth: 3
      lines: 5000
      extensions:
        - php
        - asp
        - aspx
        - ashx
        - asmx
        - jsp
        - jspx
        - cfm
        - zip
        - conf
        - config
        - xml
        - json
        - yml
        - yaml
    nuclei:
      mode: severe
    wayback:
      urls: true
    teams:
      event_types:
        - VULNERABILITY
      min_severity: HIGH
```

**Logs**
Scan not yet completed, results are from the events sent to teams
